<?php

namespace PrestaShop\Module\PsFixturesCreator;

use CartRule;
use Faker\Generator as Faker;

class CartRuleCreator
{
    private Faker $faker;

    public function __construct(Faker $faker)
    {
        $this->faker = $faker;
    }

    public function generate(int $number, int $idLang): void
    {
        for ($i = 0; $i < $number; ++$i) {
            $this->createCartRule($idLang, $i);
        }
    }

    private function createCartRule(int $idLang, int $cartRuleNumber): void
    {
        $cartRule = new CartRule();
        $cartRule->name = [$idLang => 'Fake Cart Rule ' . ($cartRuleNumber + 1)];
        $cartRule->description = 'Generated by the Faker library';
        $cartRule->code = strtoupper($this->faker->bothify('FAKE-CART-RULE-????'));
        $cartRule->quantity = $this->faker->numberBetween(1, 100);
        $cartRule->quantity_per_user = $this->faker->numberBetween(1, 10);
        $cartRule->priority = $this->faker->numberBetween(1, 10);
        $cartRule->partial_use = $this->faker->boolean(50);
        $cartRule->minimum_amount = $this->faker->randomFloat(2, 0, 500);
        $cartRule->minimum_amount_currency = 1; // Change this value according to the currencies available in your store
        $cartRule->reduction_percent = $this->faker->numberBetween(10, 90);
        $cartRule->free_shipping = $this->faker->boolean(50);
        $cartRule->active = true;

        // Set the date range for the cart rule
        $startDate = $this->faker->dateTimeBetween('-1 year', 'now');
        $endDate = $this->faker->dateTimeBetween($startDate, '+1 year');
        $cartRule->date_from = $startDate->format('Y-m-d H:i:s');
        $cartRule->date_to = $endDate->format('Y-m-d H:i:s');

        $cartRule->add();
    }
}
