<?php

namespace PrestaShop\Module\PsFixturesCreator\Creator;

use Faker\Generator as Faker;
use Product;

class ProductCreator
{
    private Faker $faker;

    public function __construct(Faker $faker)
    {
        $this->faker = $faker;
    }

    public function generate(int $number, int $idLang): void
    {
        for ($i = 0; $i < $number; ++$i) {
            $this->createProduct($idLang, $i);
        }
    }

    private function createProduct(int $idLang, int $productNumber): void
    {
        $product = new Product();
        $productName = 'Fake Product ' . ($productNumber + 1);

        $product->name = [$idLang => $productName];
        $product->description = 'This is a fake product generated by the Faker library.';
        $product->description_short = 'Generated by the Faker library.';
        $product->price = $this->faker->randomFloat(2, 1, 1000);
        $product->reference = $this->faker->bothify('FAKE-PRODUCT-????');
        $product->active = true;

        $product->add();

        $categories = [2, 3, 4];
        $product->updateCategories($categories);
    }
}
